DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
     ID INT AUTO_INCREMENT,
     MOBILE VARCHAR(11) NOT NULL COMMENT '手机号',
     PASSWORD VARCHAR(20) NOT NULL COMMENT '密码',
     DATE DATE COMMENT '注册日期',
     PRIMARY KEY (ID)
);






DROP TABLE IF EXISTS CAR;

CREATE TABLE CAR (
     ID INT AUTO_INCREMENT,
     BRAND VARCHAR(20) NOT NULL COMMENT '品牌',
     MODEL VARCHAR(20) NOT NULL COMMENT '型号',
     SEAT INT COMMENT '座数',
     PRICE DECIMAL(15,2) COMMENT '售价（万）',
     DATE DATE COMMENT '上市日期',
     PRIMARY KEY (ID)
);
